### ISSUE TITLE
Can't find symbol '_mysql_plugin_interface_version_' in library

### ISSUE THREAD

**Issue by anubhavsinha** [y-ken/mysql-udf-http#2]
MariaDB [(none)]> install soname 'mysql-udf-http';
ERROR 1127 (HY000): Can't find symbol '_mysql_plugin_interface_version_' in library
MariaDB [(none)]> 

OS: Ubuntu 16.04 LTS

ubuntu@ip-172-31-3-190:/usr/lib/mysql/plugin$ ls -l
...
...
...
-rwxr-xr-x 1 root root     897 Aug 20 19:35 mysql-udf-http.la
lrwxrwxrwx 1 root root      23 Aug 20 19:35 mysql-udf-http.so -> mysql-udf-http.so.0.0.0
lrwxrwxrwx 1 root root      23 Aug 20 19:35 mysql-udf-http.so.0 -> mysql-udf-http.so.0.0.0
-rwxr-xr-x 1 root root   18736 Aug 20 19:35 mysql-udf-http.so.0.0.0
...
...
...

**Comment by anubhavsinha** [comment]
ubuntu@ip-172-31-3-190:/usr/lib/mysql/plugin$ echo $CXXFLAGS
-DMYSQL_DYNAMIC_PLUGIN -Wall -shared

I ran configure with these flags in the environment

**Comment by anubhavsinha** [comment]
Also tried with
ubuntu@ip-172-31-3-190:~/mysql-udf-http-1.0$ echo $CXXFLAGS
-DMYSQL_DYNAMIC_PLUGIN -Wall -shared -fPIC

**Comment by fanyhawu** [comment]
you should add 'MYSQL_DYNAMIC_PLUGIN' preprocessor when compiling the mysql engine

**Comment by y-ken** [comment]
thanks!

**Comment by aiyengara** [comment]
> you should add 'MYSQL_DYNAMIC_PLUGIN' preprocessor when compiling the mysql engine

Can you please help i am stuck at the same point. i have tried everything but yet getting the error ERROR 1127 (HY000): Can't find symbol '_mysql_plugin_interface_version_' in library

**Comment by aiyengara** [comment]
> you should add 'MYSQL_DYNAMIC_PLUGIN' preprocessor when compiling the mysql engine
how do we do that, i am very confused i am currently doing it like this
./configure --prefix=/usr/local/mysql-udf-http/ --with-mysql=/usr/bin/mysql_config
